previewsEnabled: true
services:
  - type: redis
    name: test-redis
    plan: free
    ipAllowList: []
  - type: pserv
    env: docker
    name: test-worker
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: test-redis
          property: connectionString